<?if($this->errMsg):?>
<script>
    alert('<?=$this->errMsg?>');
</script>
<?endif;?>

<div class="row">
    
    <div id='login' class="col-md-4 col-lg-offset-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?='Login'?></h3>
            </div>
            <form class="form-horizontal" role="form" method="POST" action="<?php echo $this->url('autenticar'); ?>">
            <div class="panel-body">
                <div class="form-group">
                    <label for="emailTxt" class="col-lg-3 col-md-3 control-label">Email:</label>
                    <div class="col-lg-9 col-md-9">
                        <input type="email" name="emailTxt" class="form-control" id="emailTxt" placeholder="email@exemplo.com">
                    </div>
                </div>
                <div class="form-group">
                    <label for="senhaPwd" class="col-lg-3 col-md-3 control-label">Senha:</label>
                    <div class="col-lg-9 col-md-9">
                        <input type="password" name="senhaPwd" class="form-control" id="senhaPwd" placeholder="senha">
                    </div>
                </div>
            </div>
            <div class="panel-footer center">
                <button type="submit" class="btn btn-default">Enviar</button>
                <!--<a href='#' class="btn btn-warning">Esqueci minha senha</a>-->
            </div>
            </form>
        </div>
    </div>
</div>
