<div class="row">
    
    <div id='a' class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Menu</h3>
            </div>
            <div class="panel-body">
                <ul class="navbar-link">
                    <li><a href="<?php echo $this->url('usuarios') ?>">Usuários</a></li>
                    <li><a href="#">Funções</a></li>
                </ul>
            </div>
        </div>
    </div>
   
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Usuários</h3>
            </div>
            <div class="panel-body">
                <div class="col-sm-2">
                    <a href="<?=$this->url('usuarios', array('action' => 'adicionar'))?>" class="btn btn-success btn-add" title="Novo"><span class="glyphicon glyphicon-plus"></span>Novo usuário</a>
                </div>
                <form method="GET" action="<?=$this->url('usuarios', array('action' => 'buscar'))?>">
                    <div class="col-sm-offset-4 col-sm-5">
                        <input type="text" name="busca" class="form-control" placeholder="Pesquisar usuário" maxlength="150">
                    </div>
                    <div class="col-sm-1">
                        <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-search"></span></button>
                        </a>
                    </div>
                </form>
                <table class="table table-striped table-bordered table-hover">
                    <tr>
                        <th>Matrícula</th>
                        <th>Nome</th>
                        <th>Email</th>
                        <th>Data de criação</th>
                        <th>Ativo</th>
                        <th>&nbsp;</th>
                    </tr>
                    <? foreach ($this->usuarios as $usuario): ?>
                        <tr>
                            <td class="col-sd-1"><?= $usuario->getMatricula().'-'.$usuario->getDigito() ?></td>            
                            <td class="col-sd-1"><?= $usuario->getNome() ?></td>            
                            <td class="col-sd-1"><?= $usuario->getEmail() ?></td>            
                            <td class="col-sd-1"><?= $usuario->getDataCriacao()->format('d/m/Y') ?></td>            
                            <td class="col-sd-1">
                                <?if($usuario->isAtivo()): ?>
                                    <img src="<?php echo $this->basePath('img/ativo.png') ?>">
                                <?else:?>
                                    <img src="<?php echo $this->basePath('img/inativo.png') ?>">
                                <?endif;?>
                            </td>
                            <td class="col-sd-2">
                                <a class="btn btn-xs btn-info" title="Visualizar" href="/usuarios/visualizar/<?=$usuario->getIdUsuario()?>"><span class="glyphicon glyphicon-new-window"></span></a>
                                <a class="btn btn-xs btn-warning" title="Editar" href="/usuarios/editar/<?=$usuario->getIdUsuario()?>"><span class="glyphicon glyphicon-edit"></span></a>
                                <a class="btn btn-xs btn-danger" title="Excluir" href="/usuarios/excluir/<?=$usuario->getIdUsuario()?>"><span class="glyphicon glyphicon-floppy-remove"></span></a>
                            </td>
                        </tr>
                    <? endforeach; ?>
                </table>

                <?php
                // add at the end of the file after the table
                echo $this->paginationControl(
                        // the paginator object
                        $this->usuarios,
                        // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
                        'sliding',
                        // the partial to use to render the control
                        array('partial/paginator.phtml', 'Usuarios'),
                        // the route to link to when a user clicks a control link
                        array(
                    'route' => 'usuarios',
                    'orderby' => $this->orderby,
                        )
                );
                ?>
            </div>
        </div>
    </div>
    
</div>

<? $this->headScript()->captureStart(); ?>
$(document).ready(function (){
    $('.btn-danger').on('click', function () {
        var msg = 'Tem certeza que deseja realizar esta operação?';
        return confirm(msg);
    });
 });
 <? $this->headScript()->captureEnd(); ?>