<?php 

if($this->tipoProduto!=NULL){
    $id = $this->tipoProduto->getIdTipoProduto();
    $descricao = $this->tipoProduto->getDescricao();
    if($this->tipoProduto->getTipoPai())
        $_tipoProduto = $this->tipoProduto->getTipoPai()->getDescricao();
    else
        $_tipoProduto = NULL;
}  

?>
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Adicionar novo tipo de produto</h3>
            </div>
            <?php if($this->tipoProduto == NULL):?>
                <form class="form-horizontal" id="tipoproduto-form" role="form" method="POST" action="<?php echo $this->url('tiposproduto', array('action' => 'adicionar')); ?>">
            <?php else:?>
                <form class="form-horizontal" id="tipoproduto-form" role="form" method="POST" action="<?php echo $this->url('tiposproduto', array('action' => 'editar', 'id' => $id)); ?>">
            <?php endif;?>
                    
            <div class="panel-body">
                <div class="form-group">
                    <label for="tipoPaiSlct" class="col-lg-3 col-md-3 control-label">Tipo de produto pai:</label>
                    <div class="col-lg-9 col-md-9">
                        <select name="tipoPaiSlct" class="form-control" id="tipoPaiSlct">
                            <option>----Selecione um tipo de produto----</option>
                            
                            <?  foreach ($this->tiposProduto as $tipoProduto):?>
                                <?if($id != $tipoProduto->getIdTipoProduto()):?>
                                    <?if($tipoProduto->getDescricao() == $_tipoProduto):?>
                                        <option value="<?=$tipoProduto->getIdTipoProduto()?>" selected="selected"><?=$tipoProduto->getDescricao()?></option>
                                    <?else:?>
                                        <option value="<?=$tipoProduto->getIdTipoProduto()?>"><?=$tipoProduto->getDescricao()?></option>
                                    <?endif;?>
                                <?endif;?>
                            <?  endforeach;?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="descricaoTxt" class="col-lg-3 col-md-3 control-label">Descrição:</label>
                    <div class="col-lg-9 col-md-9">
                        <input type="text" name="descricaoTxt" class="form-control" 
                               id="descricaoTxt" placeholder="Tipo de produto de exemplo"
                               value="<?=$descricao?>">
                    </div>
                </div>
            </div>
            <div class="panel panel-footer center">
                <a href="<?=$this->url('tiposproduto', array('action' => 'index'))?>" class="btn btn-default" title="Voltar"><span class="glyphicon glyphicon-backward"></span> Voltar</a>
                <button type="submit" class="btn btn-default">Enviar</button>
            </div>
        </div>
    </div>
</div>

<div id="dialog" title="Erro">

</div>

<? $this->headScript()->captureStart(); ?>

$(document).ready(function(){
    $('input[type=text]').keyup(function() {
        $(this).val($(this).val().toUpperCase());
    });
 
    $( "#dialog" ).dialog({
        autoOpen: false,
        modal: true,
        close: function( event, ui ) {
            $( this ).empty();
        },
        buttons: {
            Ok: function() {
                $( this ).empty();
                $( this ).dialog( "close" );
            }
        },
        show: {
            effect: "blind",
            duration: 100
        },
        hide: {
            effect: "blind",
            duration: 100
        }
    });

    $('#tipoproduto-form').validate({
        debug: false,
        onkeyup: false,
        errorClass: "invalid-input",
        errorPlacement: function(error,element) {
            error.appendTo("#dialog");
            $( "#dialog" ).dialog('open');
            return true;
        },
        
    });
    
    $('#descricaoTxt')
            .rules("add", {
                required: true,
                minlength: 5,
                maxlength: 255,
                messages: {
                    required: "A descricao do tipo de produto é obrigatório.",
                    minlength: "A descricao do tipo de produto deve ter no mínimo 5 caracteres.",
                    maxlength: "A descricao do tipo de produto deve ter no máximo 255 caracteres.",
                }
    });
});

<? $this->headScript()->captureEnd(); ?>