<?
/*
 * Copyright (C) 2014 Irving Fernando de Medeiros Oliveira
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>
<?php echo $this->doctype(); ?>


<html lang="pt_BR">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Prefeitura Municipal de Duque de Caxias - Cadastro de Produtos')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('author', 'Irving Fernando de Medeiros Oliveira')
            ->appendName('author', 'João Batista Drumond M Barros')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendName('keywords', 'Zend Framework 2, zf2, php,
                duque de caxias, caxias, rio de janeiro, rj, prefeitura, municipio, licitação,
                programa do governo, controle interno, ciência, tecnologia, sistemas')
            ->appendHttpEquiv('Content-Language', 'pt-BR')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/960_16_col.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
                ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/jquery.mask.min.js')
            ->prependFile($this->basePath() . '/js/additional-methods.min.js')
            ->prependFile($this->basePath() . '/js/jquery.validate.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div class="container_16" id="header"></div>
        <div class="container_16" id="content">
            <?php if($this->usuarioNivel != 'guest'): ?>
                <div class="navbar navbar-collapse" id="menu">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="#">Preços</a>
                        </li>
                        <li <?=$this->MenuAtivo($this->url('unidades'))?>>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                Produtos <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Cadastro de produtos</a></li>
                                <li><a href="#">Cadastro de tipos de produto</a></li>
                                <li><a href="/unidades">Cadastro de unidades de medida</a></li>
                            </ul>
                        </li>
                        <li ><a href="#">Secretarias</a></li>
                        <li><a href="#">Usuários</a></li>
                        <li><a href="/logout">Sair</a></li>
                    </ul>
                </div>
            <?php endif;?>
            <?php echo $this->message(); ?>
            <?php echo $this->content; ?>
            
            <br/>
            <div id="footer">
                <div id="text-footer">
                    <p><b>Secretaria Municipal de Governo</b></p>
                    <p>Alameda Dona Esmeralda, 206 - Jd. Primavera - Duque de Caxias - RJ</p>
                    <p>Cep: 25215-260 - Tels: (21) 2773-6203 / (21) 2776-1577 - E-mail: smg@duquedecaxias.rj.gov.br</p>
                    <p>2013 <?php if(date("Y")!= "2013") echo "- ".date("Y");?> - Este é um <a href="http://www.gnu.org" target="_blank">software livre</a> e é regido sobre a licença <a href="http://www.gnu.org/licenses/gpl.txt" target="_blank">GPLv3</a>.</p>    
                </div>
            </div>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
