<?php 

if($this->unidade!=NULL){
    $id = $this->unidade->getIdUnidade();
    $descricao = $this->unidade->getDescricao();
}  
?>
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Adicionar nova unidade</h3>
            </div>
            <?php if($this->unidade == NULL):?>
                <form class="form-horizontal" role="form" method="POST" action="<?php echo $this->url('unidades', array('action' => 'adicionar')); ?>">
            <?php else:?>
                <form class="form-horizontal" role="form" method="POST" action="<?php echo $this->url('unidades', array('action' => 'editar', 'id' => $id)); ?>">
            <?php endif;?>
                    
            <div class="panel-body">
                <div class="form-group">
                    <label for="descricaoTxt" class="col-lg-3 col-md-3 control-label">Descrição:</label>
                    <div class="col-lg-9 col-md-9">
                        <input type="text" name="descricaoTxt" class="form-control" 
                               id="descricaoTxt" placeholder="Unidade de exemplo"
                               value="<?=$descricao?>">
                    </div>
                </div>
            </div>
            <div class="panel panel-footer center">
                <button type="submit" class="btn btn-default">Enviar</button>
            </div>
        </div>
    </div>
</div>