<div class="row">
    <div class="col-md-10 col-sm-offset-1">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Unidades</h3>
            </div>
            <div class="panel-body">
                <div class="col-sm-2">
                    <a href="<?=$this->url('unidades', array('action' => 'adicionar'))?>" class="btn btn-success btn-add" title="Novo"><span class="glyphicon glyphicon-plus"></span>Nova unidade</a>
                </div>
                <form method="GET" action="<?=$this->url('unidades', array('action' => 'buscar'))?>">
                    <div class="col-sm-offset-4 col-sm-5">
                        <input type="text" name="busca" class="form-control" placeholder="Pesquisar unidades" maxlength="150">
                    </div>
                    <div class="col-sm-1">
                        <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-search"></span></button>
                        </a>
                    </div>
                </form>
                <table class="table table-striped table-bordered table-hover">
                    <tr>
                        <th>Descrição</th>
                        <th>&nbsp;</th>
                    </tr>
                    <? foreach ($this->unidades as $key => $unidade): ?>
                        <tr>
                            <td class="col-sd-2"><?= $unidade->getDescricao() ?></td>               
                            <td class="col-sd-2 btns">
                                <a class="btn btn-xs btn-info" title="Visualizar" href="/unidades/visualizar/<?=$unidade->getIdUnidade()?>"><span class="glyphicon glyphicon-new-window"></span></a>
                                <a class="btn btn-xs btn-warning" title="Editar" href="/unidades/editar/<?=$unidade->getIdUnidade()?>"><span class="glyphicon glyphicon-edit"></span></a>
                                <a class="btn btn-xs btn-danger" title="Excluir" href="/unidades/excluir/<?=$unidade->getIdUnidade()?>"><span class="glyphicon glyphicon-floppy-remove"></span></a>
                            </td>
                        </tr>
                    <? endforeach; ?>
                </table>

                <?php
                // add at the end of the file after the table
                echo $this->paginationControl(
                        // the paginator object
                        $this->unidades,
                        // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
                        'sliding',
                        // the partial to use to render the control
                        array('partial/paginator.phtml', 'Unidades'),
                        // the route to link to when a user clicks a control link
                        array(
                    'route' => 'unidades',
                    'orderby' => $this->orderby,
                        )
                );
                ?>
                <?php if(isset($_GET['busca'])):?>
                    <div class="panel-footer center">
                        <a href="<?=$this->url('unidades', array('action' => 'index'))?>" class="btn btn-default" title="Voltar"><span class="glyphicon glyphicon-backward"></span> Voltar</a>
                    </div>
                <?php endif;?>
            </div>
        </div>
    </div>
</div>

<? $this->headScript()->captureStart(); ?>
$(document).ready(function (){
    $('.btn-danger').on('click', function () {
        var msg = 'Tem certeza que deseja realizar esta operação?';
        return confirm(msg);
    });
 });
 <? $this->headScript()->captureEnd(); ?>