<?
if($this->unidade){
    $id = $this->unidade->getIdUnidade();
    $descricao = $this->unidade->getDescricao();
}
?>
<div class="row">
    <div class="col-md-10 col-sm-offset-1">
        <div class="panel">
            <div class="panel-heading list-group">
                <h3 class="panel-title">Visualizar unidade</h3>
            </div>
            <div class="panel-body">
                <div>
                    <p class="col-lg-3 col-md-3 list-group-item-text">Id:</p>
                    <div class="col-lg-9 col-md-9">
                        <p class="list-group-item-text" id="nomeTxt"><?=$id;?></p>
                    </div>
                </div>
            </div>
            <div class="panel-body">
                <div>
                    <p class="col-lg-3 col-md-3 list-group-item-text">Descricao:</p>
                    <div class="col-lg-9 col-md-9">
                        <p class="list-group-item-text" id="nomeTxt"><?=$descricao;?></p>
                    </div>
                </div>
            </div>
            <div class="panel-footer center">
                <a href="<?=$this->url('unidades', array('action' => 'index'))?>" class="btn btn-default" title="Voltar"><span class="glyphicon glyphicon-backward"></span> Voltar</a>
            </div>
        </div>
    </div>
</div>